theme = "catppuccin_mocha"

[editor]
line-number = "relative"
completion-timeout = 0
idle-timeout = 0
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# [editor.lsp]
# display-inlay-hints = true

[editor.indent-guides]
render = true
